apiVersion: batch/v1
kind: Job
metadata:
  name: tsunami
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: tsunami
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tsunami        
    spec:
      imagePullSecrets:
      - name: myregistrykey
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
      initContainers:
      - name: tsunami
        image: "{{ .Values.global.image.repository }}/tsunami:{{ .Values.global.image.tag }}"
        imagePullPolicy: "{{ .Values.global.image.pullPolicy }}"
        volumeMounts:
        - name: reports
          mountPath: /usr/tsunami/logs        
        - name: hosts
          mountPath: /usr/tsunami/hosts.txt
          subPath: hosts.txt
      containers:
      - name: ses-py
        image: "{{ .Values.global.image.repository }}/ses-py:{{ .Values.global.image.tag }}"
        imagePullPolicy: "{{ .Values.global.image.pullPolicy }}"  
        command: [ "python3", "ses.py" ]
        env:
        - name: RECIPIENT
          value: "{{ .Values.global.email.recipient }}"
        - name: SENDER
          value: "{{ .Values.global.email.sender }}"
        - name: AWS_REGION
          value: "{{ .Values.global.aws.region }}"
        - name: AWS_ACCESS_KEY_ID
          value: "{{ .Values.global.aws.username }}"
        - name: AWS_SECRET_ACCESS_KEY
          value: "{{ .Values.global.aws.password }}"
        volumeMounts:
        - name: reports
          mountPath: /app/logs
        - name: sespy
          mountPath: /app
      volumes:
      - name: reports
        emptyDir: {}
      - name: hosts
        configMap:
          name: hosts
          defaultMode: 0744
      - name: sespy
        configMap:
          name: sespy
          defaultMode: 0744    
